### ISSUE TITLE
Allowing user to set CommandKey and ThreadPool

### ISSUE THREAD

**Issue by pratikkumar19** [yammer/tenacity#35]
Currently in tenacity command , the property key given by user is used as same for command key and threadpool key. This does not allow the user the freedom of executing various command on same threadpool

**Comment by chrisgray** [comment]
When the project first started we tried to avoid mixing and matching different threadpools with different keys and vice versa because we found it became pretty hard to reason about past behavior if these threadpools and which keys ran in them change (observing metrics, etc.). A little context :-)

The library forces you at the moment to adhere to that, but I don't see any reason why we shouldn't add the ability to make it so you can choose the propertykey you want to use for the command key and threadpool key. I'll get this in the next release.

**Comment by chrisgray** [comment]
Should be available in 0.8.1!
