### ISSUE TITLE
Tenacity not adopting Breakerbox configuration

### ISSUE THREAD

**Issue by mlamina** [yammer/tenacity#37]
My setup is the following:

- Tenacity 0.8.2
- Breakerbox 4.3

My breakerbox cluster config: https://gist.github.com/mlamina/172dc7c982dc5a00fe9a5ba6f4697acb
My tenacity config: https://gist.github.com/mlamina/29ed67b0e087175ad70569de48514380

Everything seems to be set up correctly. Breakerbox pulls the dependency keys from Tenacity and Tenacity is polling the correct archaius endpoint on Breakerbox. However, Breakerbox marks all property keys as "Unsynchronized" and the service using Tenacity is always using the timeout settings from my yaml file, according to this method:

`TenacityCommand.getCommandProperties(DependencyKeys.AF_METADATA).executionTimeoutInMilliseconds().get()`

![screen shot 2016-06-09 at 13 32 28](https://cloud.githubusercontent.com/assets/474314/15928346/ab49e5b4-2e46-11e6-9169-22878d54e890.png)

Using curl, I checked following endpoints successfully:

`http://auth-facade.staging.svc.cluster.local:8081/tenacity/configuration/AF_METADATA`
`http://breakerbox.management.svc.cluster.local/archaius/staging`

Am I missing something here? The Breakerbox logs are not giving any hints either. I believe my service implementation is not the problem, because if I add the Breakerbox service itself as a cluster (just like in the Tenacity guide), it shows the same behavior.

**PS**: I don't know if this is related, but Breakerbox only shows me metrics for calls which make use of `TenacityCommand`, but not the ones that use `TenacityJerseyClientBuilder`.

**Comment by chrisgray** [comment]
Can you see if you have one of the execution isolation strategy radio buttons selected? This is the most common case for not having this sort of thing synchronized. I'm working at the moment to update the UI so parts of the form that are out of sync with the remote instances are much easier to recognize!

I'm also working on a fix to Breakerbox so that when in doubt it can at least highlight what the remote instance is running and populate those fields so that as a user you can see what the defaults are and what the remote instance is running and make the best choice when it comes to configuring that property key.

As for the TenacityJerseyClientBuilder, it does leverage TenacityPropertyKey, but like you said it doesn't generate metrics off of it. It only leverages the execution timeout set for that property key and uses it to set the readTimeout configuration parameter for the JerseyClient on each request that it makes.

**Comment by mlamina** [comment]
As for the synchronization issue: It works now! Although I find it non-intuitive that I  have to manually click select the execution isolation strategy in the UI in order to get the sync working. Maybe it should be selected by default?

Too bad TenacityJerseyClientBuilder doesn't generate metrics, I find it very handy to use. However, It would be great if the README contained a notice about that. I could imagine not being the only one wondering about that.

**Comment by chrisgray** [comment]
I agree with you that it's very non-intuitive! Working on adjusting the UX so it's cleaner, more upfront with what is missing, as well as filling in defaults.

I'll go ahead and update the readme with more clarification around the metrics and TenacityJerseyClientBuilder.

**Comment by mlamina** [comment]
Cool! Thanks for your help and keep up the good work :)
